export const ADD_PRODUCT_BASKET='ADD_PRODUCT_BASKET';
export const GET_NUMBERS_BASKETS='GET_NUMBERS_BASKETS';
export const INCREASE_QUANTITY='INCREASE_QUANTITY';
export const DECREASE_QUANTITY='DECREASE_QUANTITY'